### ISSUE TITLE
Failed to save log: Required POST argument 'content' not found

### ISSUE THREAD

**Issue by Kichura** [aternosorg/mclogs#100]
Sometimes when pasting any log-related files into the text field and then saving, it will result in that error above.

**Comment by Soapy7261** [comment]
I believe this may be related to this -> https://github.com/aternosorg/mclogs/issues/42

**Comment by Kichura** [comment]
The reality is that this was not caused by API scripts as instead the website itself was used for saving the logs, therefore this doesn't really add up to your issue.

**Comment by Soapy7261** [comment]
What?
The script was not at fault, the API was at fault due to PHP post limit
How big is your log that makes that error occur?

**Comment by Kichura** [comment]
> What? The script was not at fault, the API was at fault due to PHP post limit How big is your log that makes that error occur?

i think the last one i tried to review during support in viaversion was around 8/9 MBs and then the one after was less of all things. *(both of which are already resolved by the time that error was worked around)*

**Comment by JulianVennen** [comment]
Mclogs only stores 10 MB and 25 000 lines. These limits are applied on the backend, and longer log files are shortened automatically.
Unfortunately, the PHP post size limit mentioned in #42 can cause logs that are much larger than that to not work correctly.

We should probably apply the limit for lines and size on the frontend as well to prevent this.
