### ISSUE TITLE
wrong server software 

### ISSUE THREAD

**Issue by Dobby-progam** [aternosorg/mclogs#12]
when there is a 
Fabric server log shered It shows up als a vanilla server 
![afbeelding](https://user-images.githubusercontent.com/87517487/126486438-dee52dab-bb90-47cc-9850-903d9363233a.png)

**Comment by matthi4s** [comment]
The detection works based on specific log entries that identify the server software. Fabric doesn't log anything that can be used to reliably detect it when it crashes immediately on launch.

**Comment by Dobby-progam** [comment]
okay can I Close this
