### ISSUE TITLE
Original Precision Scope not being able to craft it or the recipe is not there in JEI

### ISSUE THREAD

**Issue by ShadowkingREEEE** [aternosorg/mclogs#122]
You need the Precision scope to create the Scope for the Turrets from the basic immersive engineering and immersive intelligence guns and items/tools like the Scope for the guns, Tools Binoculars, Technicians Headgear and Infiltrators Headgear.

**Comment by Soapy7261** [comment]
> This is not a place to get help with your Minecraft modpack.
mclo.gs is just a site that you can use to share your logs and crash reports.

https://github.com/aternosorg/mclogs/issues/109#issuecomment-1997666948
