### ISSUE TITLE
im need help

### ISSUE THREAD

**Issue by Angelessq** [aternosorg/mclogs#123]
I was building mods for the game with my friends, everything seems to be fine, but when 10-20 minutes pass, it immediately crashes.Please help me!   Logs: https://mclo.gs/fPnIWY4

**Comment by MiataBoy** [comment]
This isn't the place to get help with your server. This is for support with the logging software itself or to bring issues to the team's attention.

**Comment by Angelessq** [comment]
< This isn't the place to get help with your server. This is for support with the logging software itself or to bring issues regarding the software itself to the team's attention.

and where can I get help?

**Comment by MiataBoy** [comment]
Through support@aternos.org or the discord:
https://discord.aternos.org
