### ISSUE TITLE
Add API endpoint to query storage limits

### ISSUE THREAD

**Issue by Kationor** [aternosorg/mclogs#125]
mclo.gs truncates logs to a configurable size, but does not currently have a simple way of querying those limits.
Adding an API endpoint to retrieve storage limits (`maxLines`, `maxLength`, maybe `storageTime`) would allow applications to do some pre-processing on their end, such as [truncating in a way that keeps lines near the end](https://github.com/PrismLauncher/PrismLauncher/pull/2737) or simply pre-truncating logs to save bandwidth.

**Comment by matthi4s** [comment]
Thanks for the suggestion, the endpoint is now available here: https://api.mclo.gs/1/limits
