### ISSUE TITLE
new auto detection

### ISSUE THREAD

**Issue by Dobby-progam** [aternosorg/mclogs#19]
hello, it will be very nice if you also want to add aternos errors to the automatic detection 

Like` [Aternos System/ERROR]: Server was stopped because it took too long to start. Try reducing the load to avoid this in the future.`
So that we don't always have to scroll through 1000 logs before we see this (forge server)

I hope it's possible 
Dobbie

**Comment by JulianVennen** [comment]
You can easily scroll down by clicking the lines button at the top op the page.
Aternos specific error messages don't really belong into mclogs/codex.

**Comment by JulianVennen** [comment]
what?

**Comment by Dobby-progam** [comment]
![afbeelding](https://user-images.githubusercontent.com/87517487/160673292-7badfc82-1f69-42e4-a79d-f1d181c4e01d.png)
those numbers at the side

**Comment by JulianVennen** [comment]
If you click the line count in the top right, it will take you to the end of the log
![image](https://user-images.githubusercontent.com/45244473/160673655-2247d040-1b73-408c-9939-38516b5b4410.png)

**Comment by Dobby-progam** [comment]
ok thanks for your patience
