### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by RealmKebab** [aternosorg/mclogs#29]
make it so when a player shares their crash logs, or when the server crashes and the log was sent
it highlights the error and whats causing it
so it makes exaroton and Aternos discord support easier

**Comment by JulianVennen** [comment]
We already highlight errors in red and try to detect common problems to offer solutions for them.
There's no magic way to know what exactly causes a crash.
There are dozens of server softwares which log their crashes completely differently.
That also depends on where (in the server code) exactly the crash occurred and what Minecraft/software version the server is running.
