### ISSUE TITLE
add quilt support

### ISSUE THREAD

**Issue by DioEgizio** [aternosorg/mclogs#30]
[Quilt](https://quiltmc.org/) is a new modding toolchain. Currently, when someone uses Quilt mclo.gs shows server software vanilla

![image](https://user-images.githubusercontent.com/83089242/168468204-18beb85a-4134-4b01-a0f4-abbe7d0e65b0.png)

**Comment by JulianVennen** [comment]
Thanks for the suggestion.
I created a pull request for this in our library that detects those things: https://github.com/aternosorg/codex-minecraft/pull/23
After that has been merged, we can update it in mclogs

**Comment by DioEgizio** [comment]
It's merged

**Comment by DioEgizio** [comment]
Thanks!
