### ISSUE TITLE
Insights API

### ISSUE THREAD

**Issue by Soapy7261** [aternosorg/mclogs#32]
Using the API, It should be able to see the errors and possible solutions from the automatic error detection since that's one of mclogs's main features

**Comment by Soapy7261** [comment]
Sort of like 
'success': True, 'id': 'BLANK', 'url': 'https://mclo.gs/BLANK', 'raw': 'https://api.mclo.gs/1/raw/BLANK, 'errors': 'COUNT', 'errorurl': 'https://api.mclo.gs/1/errors/BLANK'
GET: https://api.mclo.gs/1/errors/BLANK/COUNT
'success': True, 'error': 'InsertError', 'solution': 'InsertSolution'

**Comment by JulianVennen** [comment]
Requiring a new request for every single detection is not a good idea. We should just return a list of insights or maybe a separate list for informations and errors.

**Comment by Soapy7261** [comment]
Doesn't sound like a bad idea if its documented well enough

**Comment by Amgelo563** [comment]
I don't see many situations where you'd only want to see how many errors there are, but not which, even if you did want that then probably a better idea would be a `GET` for information and another one for the list, not a request for each error.

This does seem a bit over complicated though, I think just a simple `GET` that returns info and all the errors (as Julian mentioned) would probably be the most useful for most situations.

Overall though this indeed seems like a useful feature, would like to see it implemented.

**Comment by Soapy7261** [comment]
I mean the auto detecting errors and solutions like 
![image](https://user-images.githubusercontent.com/81933267/180672254-644f8c8e-e94d-4dc6-91ad-2697e5d7e15b.png)

**Comment by JulianVennen** [comment]
Mclogs detects insights. Insights can either be a "problem" (that's on your screenshot) or an "information" (e.g. Minecraft version).
If we expose on of them in the API we can expose both.

**Comment by Soapy7261** [comment]
Well, I guess seeing the version isn't that bad

**Comment by Soapy7261** [comment]
Or maybe more like
'success': True, 'id': 'BLANK', 'url': 'https://mclo.gs/BLANK', 'raw': 'https://api.mclo.gs/1/raw/BLANK, 'errors': 'COUNT', 'errorurl': 'https://api.mclo.gs/1/errors/BLANK'
GET: https://api.mclo.gs/1/errors/BLANK
Return:
errors = {
    '1': 'The world was saved with mod surge which appears to be missing.',
}
solutions = {
    '1': 'Install the mod surge',
    '1.5': 'Do nothing. This problem might fix itself',
}
Yeah i know the 1.5 isn't the best but its for the example

**Comment by JulianVennen** [comment]
This will be added but it might take some time since we might do some major changes for it

**Comment by Soapy7261** [comment]
👍

**Comment by matthi4s** [comment]
Just as a "preview", this is probably what it will look like: https://github.com/aternosorg/codex-minecraft/blob/ca222869536e20102cb5440bc8e09bba5e33605d/test/data/forge/forge-mod-dependency.json#L636

**Comment by Soapy7261** [comment]
👍

**Comment by matthi4s** [comment]
Done, you can find the documentation here: https://api.mclo.gs/
