### ISSUE TITLE
No me deja abrir mi servidor de alternos pero como yo no sé que problema tenga puede ayudarme a solucionarlo porfavor

### ISSUE THREAD

**Issue by TopGustavito** [aternosorg/mclogs#34]
https://mclo.gs/B5UvCxB
Ese es mi server puede revisar que ocasiona el fallo

**Comment by Alex22sv** [comment]
Aternos*
Este no es el lugar para pedir ayuda con tu servidor. Es para ayuda con problemas con mclogs.

**Comment by TopGustavito** [comment]
> Aternos* Este no es el lugar para pedir ayuda con tu servidor. Es para ayudar con problemas con mclogs.

**Comment by TopGustavito** [comment]
Porque si acá me mandó que para ver cómo me pueden ayudar

**Comment by TopGustavito** [comment]
¿Quien me puede ayudar ?

**Comment by JulianVennen** [comment]
https://support.aternos.org/hc/en-us/articles/360027235811-Contact-support
