### ISSUE TITLE
mclogs website looks weird with the new quilt modtable

### ISSUE THREAD

**Issue by DioEgizio** [aternosorg/mclogs#37]
![image](https://user-images.githubusercontent.com/83089242/186423299-e0039b5b-962c-4e18-a88d-affca785e6ed.jpg)

https://mclo.gs/A3Kfwub

**Comment by DioEgizio** [comment]
![image](https://user-images.githubusercontent.com/83089242/186423447-72dd2ccd-d9b7-4687-a998-84d5530a41ce.jpg)

Unrelated but sometimes the website is unusable on mobile without desktop mode, like now

**Comment by JulianVennen** [comment]
Which browser are you using?
Is the first screenshot also from mobile?

In both cases, the lines are wrapping for me.

**Comment by DioEgizio** [comment]
Firefox Mobile

**Comment by Dobby-progam** [comment]
I got something similar 
Using Firefox mobile 104.1.0

The Warings and errors aren't cut off correct as shown in the screenshot
