### ISSUE TITLE
Add a "raw view" page to the mclo.gs website 

### ISSUE THREAD

**Issue by me4502** [aternosorg/mclogs#4]
Hi,

A lot of plugin devs have various systems in place to automatically scan logs as they are sent in Discord chats etc. In order to not scan the HTML document (for speed and "false positive" reasons), generally raw URLs are used to scan the log file. 

Is it possible for mclo.gs to add a /raw/ URL pattern?

For example, Pastebin mirrors every `https://pastebin.com/somepaste` URL with `https://pastebin.com/raw/somepaste`. This raw URL returns only the paste contents without any HTML.

**Comment by matthi4s** [comment]
Hi, thanks for the suggestion! 

I've added an API endpoint for that: `https://api.mclo.gs/1/raw/[id]`. A bit more info is in the API docs here: https://api.mclo.gs/

**Comment by me4502** [comment]
Thanks :D
