### ISSUE TITLE
Magma 1.16.5 isn't detected

### ISSUE THREAD

**Issue by Soapy7261** [aternosorg/mclogs#41]
In the discord server a while back, it was said that [magma was detected on mclogs](https://discord.com/channels/107936397578489856/550278155789926430/669220653366247454) but [isn't any more on 1.16.5](https://mclo.gs/1akscjb), what happened?

**Comment by MiataBoy** [comment]
Magma is still being detected (as per my test in https://mclo.gs/r7fvLl8), but this specific log just seems to fail to be detected by codex. A team member can probably elaborate on that more, but eitherway the detection works

**Comment by Soapy7261** [comment]
My test was 1.16.5 so perhaps something changed, and codex can't detect it anymore

**Comment by MiataBoy** [comment]
the problem is that magma changed it's logging prefix.
This wasn't accounted for originally.
