### ISSUE TITLE
When a log is too big, mclogs misbehaves

### ISSUE THREAD

**Issue by Soapy7261** [aternosorg/mclogs#42]
When i submit a log thats about 7MB, mclogs misbehaves, the file was 7.29MB
When using the website it brings me to https://mclo.gs/undefined
When using the API, it says there is no content field
Video:
https://user-images.githubusercontent.com/81933267/197589457-45560440-e6e1-4139-ae88-9597892ff5a4.mp4

**Comment by JustRed23** [comment]
Same as aternosorg/mclogs-java#5

**Comment by UeberallGebannt** [comment]
Would it be possible to split a log into multiple links? Especially with modpacks, logs tend to get quite big and this would be a cool feature :)

**Comment by Soapy7261** [comment]
I think it'd be cool for a "See more" button at the bottom to prevent some browsers instantly crashing

**Comment by Dobby-progam** [comment]
Yes that would be useful, then support can't miss out on hidden lines where potential crucial information is located

**Comment by Soapy7261** [comment]
Also, i think it'd be good if the API told you that your log is too big instead of just throwing some random error
