### ISSUE TITLE
want support CustomSkinLoader

### ISSUE THREAD

**Issue by 8MiYile** [aternosorg/mclogs#50]
Need support CustomSkinLoader Mod's Log
https://mclo.gs/Zyny8V7

**Comment by Alex22sv** [comment]
This is not support for Minecraft servers.

**Comment by JulianVennen** [comment]
If I understand your message correctly, you're asking us to add formatting for logs created by that mod.

Is that just the latest.log or a custom file created by that mod?

**Comment by 8MiYile** [comment]
@JulianVennen 
Look like CustomSkinLoader's Custom Logs

**Comment by 8MiYile** [comment]
![截图_选择区域_20230114094916](https://user-images.githubusercontent.com/25455400/212445617-c57bda07-a491-4184-9a61-5ce931d5d49e.png)
look like this

**Comment by 8MiYile** [comment]
Hello
Are you there?

**Comment by JulianVennen** [comment]
This has been implemented now. If you find any issues with it, or you have further suggestions, please let us know
