### ISSUE TITLE
API returns 403 when logs are uploaded

### ISSUE THREAD

**Issue by JustRed23** [aternosorg/mclogs#52]
Seems like the latest changes broke the API, when uploading normal logs it seems to be returning 403 forbidden, but when random garbage text is uploaded the API will work as expected (I am using the mclogs-java repo for uploading logs if that helps)

![apitest](https://user-images.githubusercontent.com/21986809/212980150-62e50817-a56f-45e4-bde7-ed7acc53005e.png)

**Comment by JustRed23** [comment]
Might be related to #51. Not sure but make sure to give it a try

**Comment by JulianVennen** [comment]
Could you provide the log you're trying to upload?

**Comment by JustRed23** [comment]
[message-under8mb.txt](https://github.com/aternosorg/mclogs/files/10438308/message-under8mb.txt) < This one does not work

[test.txt](https://github.com/aternosorg/mclogs/files/10438311/test.txt) < This one is just garbage data, but it works

**Comment by JulianVennen** [comment]
Please try again now

**Comment by JustRed23** [comment]
> Please try again now

Yup! It seems to work now. Thanks!
