### ISSUE TITLE
mobile site is broken

### ISSUE THREAD

**Issue by itsmiir** [aternosorg/mclogs#55]
text does not wrap on the mobile site, so you have to zoom out; but the background does not continue, so it's impossible to read the text in the logs
(iPhone 12 mini, iOS 16.0)
![image](https://user-images.githubusercontent.com/12114517/213923314-da05063c-9435-47c5-9f83-8cb9e6fb332c.png)

**Comment by adriellwc** [comment]
Have you tried another browser?

**Comment by itsmiir** [comment]
> Have you tried another browser?

i've tried safari, firefox, and the browser in the discord app (which i assume to be a wrapper for safari)

**Comment by JulianVennen** [comment]
should be fixed
