### ISSUE TITLE
How big of a log can be used on your website

### ISSUE THREAD

**Issue by PhilFry25** [aternosorg/mclogs#57]
wanting to sort thew a couple of log files , and instead of uploading 3 or more, i used a script to merge the logs to one file. 
the website reads it fine. takes awhile. but when i save. it goes no way 404 . Is there a Line limit or size?

**Comment by JulianVennen** [comment]
log files above 16 MB will not be accepted by the api.
Log files below that will be shortened to 10 MB and 25k lines
