### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by zkitefly** [aternosorg/mclogs#60]
(Google Translate):

I am a player from mainland China, I hope mclogs can support multiple languages, support Simplified Chinese, Traditional Chinese, etc.

In this way, I can recommend mclogs to my friends.

Thanks♪(･ω･)ﾉ

-------------------------
我是一位来自中国大陆的玩家，我希望 mclogs 能支持多语言，支持 简体中文 、繁体中文 等

这样我就能向我身边的朋友们推荐 mclogs 。

谢谢Thanks♪(･ω･)ﾉ

**Comment by Soapy7261** [comment]
The logs themselves will always be in english since that's what you paste in, mclogs has no control over that

**Comment by zkitefly** [comment]
> The logs themselves will always be in english since that's what you paste in, mclogs has no control over that

我的意思是将 info 页面添加多语言，以及一些固定的词语如 `Versions` 等

日志内容无需多语言

---------------------

I mean to add multiple languages and some fixed words such as `Versions` to the info page

Log content does not need multiple languages

**Comment by Soapy7261** [comment]
Fair enough

**Comment by 8MiYile** [comment]
好家伙 我也来

---

@Soapy7261 look there
just website's word need a translate

for example
`paste your minecraft logs` --> `粘贴你的Minecraft日志`
`Paste your log here or ` --> `在这里粘贴你的日志或者`
`select a file` --> `选择一个文件`
`save` --> `保存`

**Comment by Dobby-progam** [comment]
I would think that it will require a rewrite of the front-end to integrate it with  crowdin

**Comment by JulianVennen** [comment]
Closed in favor of #113
