### ISSUE TITLE
Automatically detect this problem

### ISSUE THREAD

**Issue by Alex22sv** [aternosorg/mclogs#65]
I would like you to add the following message as an an automatically detected problem because it appears when the server crashes due that error, so adding it to the analysis would be helpful for users to identify what's the crash reason of the server.

- **Error message from the log**: "mod_name (mod_id) encountered an error during the event_name event phase"
- **Example message for the analysis**: "The mod 'mod_name' has encountered an error."
- **Server log for reference**: https://mclo.gs/hhwZ2Y9#L175

**Comment by JulianVennen** [comment]
WIP: https://github.com/aternosorg/codex-minecraft/pull/54
