### ISSUE TITLE
Client Mod 

### ISSUE THREAD

**Issue by Minenash** [aternosorg/mclogs#69]
I was thinking about writing a client side mod that on crash, pops up a window with the full log with a button a button to copy to clipboard, a button to go to folder, and a button to upload and copy url to clipboard (and a checkbox for automatically uploading the log, disabled by default)

Since mclogs is really helpful for modders, I want try to get the mod as known as possible. Being able to use the logo (probably modified to indicate client-ness) and having it listed on the site would help a lot. Is either of these possible?

It also could be under the org if you want it to be official and have control over the project.

I thought about PRing the mods directly to add it, but that would cause boat when used on the server, and might cause confusion for users playing single player if there's also commands.

Thanks for reading,
    Jakob

**Comment by JulianVennen** [comment]
That sounds like a useful mod, but we don't want to put our branding on something we didn't create.
A useful and well-made mod will become popular even if it's not pushed by any other project.

There also is a similar mod already (Not Enough Crashes) which uploads logs as a GitHub gist.

**Comment by Minenash** [comment]
> There also is a similar mod already (Not Enough Crashes) which uploads logs as a GitHub gist.

That mod can be problematic. Since it tries to recover, and go back to the main screen, some mods break. And also in the process of trying to add extra data, it can also cause 
(further) crashes making it harder to know the original error add can often blame the wrong mod causing extra support burden on some devs

But understand for the rest
