### ISSUE TITLE
[FEATURE] - Utilise the modrinth API

### ISSUE THREAD

**Issue by TecEash1** [aternosorg/mclogs#72]
A cool feature would be that if mclogs detects an issue related to a mod. E.g. install x mod greater or lower than the given number… then it will use the version/mod loader that it can also view in the log to send a request to the modrinth API and return links of potential mods that would act as a replacement

**Comment by Dobby-progam** [comment]
You can't send API requests for similar to this mod
And modrint isn't the only place to get mods,
Now I am not from the team, but I do see those issues

**Comment by JulianVennen** [comment]
The main problem with this is that we can't get the project ID of the mods from the log.
We only have the mod ID, which oftentimes will be different from their slug on Modrinth.
As far as I could find, Modrinth has no endpoint to search projects with a mod ID, and even if they did, there could be multiple results with the same mod ID (e.g. in case of forks).
