### ISSUE TITLE
Detect this problem

### ISSUE THREAD

**Issue by TecEash1** [aternosorg/mclogs#73]
Confused why mclogs didn’t auto detect this. This was the [log](https://mclo.gs/WbzYkXz) for reference tho, the issue was actually in the log itself:
```
A potential solution has been determined:
     - Replace mod 'Entity Model Features' (entity_model_features) 0.2.8 with any version that is compatible with:
         - cem 0.7.1_S8_1.19-1.19.2
```

**Comment by JulianVennen** [comment]
We only detected dependency problems, not incompatibilities, until now.
I created a PR for that: https://github.com/aternosorg/codex-minecraft/pull/53
