### ISSUE TITLE
Cant break any blocks on the server

### ISSUE THREAD

**Issue by Pavlozavrik** [aternosorg/mclogs#78]
https://mclo.gs/RgjDJv4

**Comment by MiataBoy** [comment]
This is not a problem with mclo.gs.

**Comment by Pavlozavrik** [comment]
> This is not a problem with mclo.gs. You'll want to review your logs for issues, and ask support of the host you're using.

What the host? It is aternos

**Comment by JulianVennen** [comment]
This is not the Aternos support.

**Comment by Pavlozavrik** [comment]
> This is not the Aternos support.
the github page named aternosorg

**Comment by JulianVennen** [comment]
This is our GitHub account, that doesn't mean that you get support for Aternos servers here.
If you were to google for literally two seconds, you would find this: https://support.aternos.org/hc/en-us/articles/360027235811-Contact-support
