### ISSUE TITLE
Minecraft 1.16.5 server crashed because of productive bees

### ISSUE THREAD

**Issue by Maddog2271** [aternosorg/mclogs#89]
[api.mclo.gs_1_raw_IUfqcFU.pdf](https://github.com/aternosorg/mclogs/files/12505082/api.mclo.gs_1_raw_IUfqcFU.pdf)
log
ive tried to get a different version of forge and of productive bees but it still wont work

**Comment by MiataBoy** [comment]
Issues in this repository or for issues with mclo.gs, not your Minecraft server. You can get help for that with the relevant Minecraft host's discord server.
