### ISSUE TITLE
Server crashing on start

### ISSUE THREAD

**Issue by xodugan** [aternosorg/mclogs#9]
Hello, im trying to start a server with forge 1.16.4 (35.1.37) with 64 mods:
AppleSkin-mc1.16.2-forge-1.0.14.jar
ars_nouveau-1.16.4-1.11.4.jar
BetterCaves-Forge-1.16.4-1.1.1.jar
BloodMagic-1.16.4-3.1.0-15.jar
Botania-1.16.4-411.jar
BotaniaAdditionsMC1.16.4-1.0.4.jar
Bountiful Baubles FORGE-1.16.3-0.0.2.jar
byg-1.1.8.jar
ChickenChunks-1.16.4-2.7.0.85-universal.jar
chocolate-1.3.0-1.16.4.jar
Chunk Pregenerator-V1.16-3.0.3.jar
citadel-1.6.0.jar
ClassicCombat-1.16.4-universal.jar
Clumps-6.0.0.15.jar
CodeChickenLib-1.16.4-3.5.1.408-universal.jar
curios-forge-1.16.5-4.0.4.0.jar
DungeonCrawl-1.16.3-2.2.4.jar
dungeons_plus-1.16.4-1.1.3.jar
eidolon-0.2.7.jar
elevatorid-1.16.4-1.7.10.jar
EnderStorage-1.16.4-2.7.1.166-universal.jar
furniture-7.0.0-pre19-1.16.3.jar
geckolib-forge-1.16.5-3.0.13.jar
gravestone-1.16.4-1.0.9.jar
iafgear-1.16.3-1.0.2.jar
iceandfire-2.1.5-1.16.4.jar
ImmersiveEngineering-1.16.4-4.1.2-129.jar
industrial-foregoing-1.16.4-3.2.8.2-6b5c95b.jar
ironchest-1.16.4-11.2.10.jar
ironfurnaces-1.16.4-2.5.8.jar
jei-1.16.4-7.6.1.71.jar
looot-1.16.4-1.0.0.3.jar
mahoutsukai-1.16.5-v1.28.0.jar
managear-1.16.3-2.2.3.jar
Mekanism-1.16.4-10.0.19.446.jar
ModularPowersuits-1.16.4-2.0.2.jar
Morpheus-1.16.4-4.2.68.jar
Neat 1.7-27.jar
NetherPortalFix_1.16.3-7.2.1.jar
nuclear_craft-1.16.4-0.6.4.jar
Numina-1.16.4-2.0.3.jar
obfuscate-0.6.0-1.16.3.jar
pamhc2foodcore-1.16.3-1.0.2.jar
Patchouli-1.16.4-48.jar
reap-1.16.4-1.0.3.jar
refinedstorage-1.9.12.jar
repurposed_structures-1.16.4-2.3.4.jar
SilentGear-1.16.3-2.5.5+213.jar
SilentLib-1.16.3-4.9.1+64.jar
sophisticatedbackpacks-1.16.4-2.1.1.153.jar
Space-Bosstools-1.16.4-4.1.jar
structure_gel-1.16.4-1.7.5.jar
The_Undergarden-1.16.5-0.4.5.jar
TheAbyss2 1.2.0 1.16.4.jar
titanium-1.16.5-3.2.6.2.jar
TrashSlot_1.16.3-12.2.1.jar
valhelsia_structures-16.0.5.jar
Vampirism-1.16.4-1.7.4.jar
walljump-forge-1.16.4-1.3.7.jar
Waystones_1.16.3-7.3.1.jar
workshopsofdoom-1.16.4-1.1.0.1.jar
Xaeros_Minimap_21.2.0.2_Forge_1.16.5.jar
XaerosWorldMap_1.11.11.2_Forge_1.16.5.jar
YungsApi-1.16.4-Forge-4.jar

So, the server has already been opened but sometimes when i try to open it, it keeps crashing, i have searched the logs but didnt found the exact mod that is causing the crash. Need help to solve this problem and want to know what mods are causing this problem. The crash log link is: https://mclo.gs/Btc2Xbp

**Comment by matthi4s** [comment]
This is not a place for support with your Minecraft server.
