### ISSUE TITLE
Expected to detect error 

### ISSUE THREAD

**Issue by TecEash1** [aternosorg/mclogs#95]
https://mclo.gs/68PbMI7

- didn’t display solutions or detect errors

**Comment by MiataBoy** [comment]
While I can't answer for the solution display part, I'm not sure what you mean with 'didn't detect errors'.
![afbeelding](https://github.com/aternosorg/mclogs/assets/34064010/4d3c3094-4803-4d46-8d79-ba137a5d4ec2)

**Comment by TecEash1** [comment]
Sorry, just provide potential solutions that were displayed 😅

**Comment by MiataBoy** [comment]
It seems fabric doesn't provide solutions, which is done by codex-minecraft:
https://github.com/aternosorg/codex-minecraft/tree/master/src/Analysis/Solution
