### ISSUE TITLE
I Keep Crashing With Modpacks

### ISSUE THREAD

**Issue by Cosmer-A** [aternosorg/mclogs#99]
https://mclo.gs/qxjGBzm 

https://mclo.gs/rplGYmj 

I'm not sure why, but every time I try to run certain mod packs on CurseForge, I keep crashing, and it would be much appreciated if anyone could explain the reason.

**Comment by Dobby-progam** [comment]
Hi, 

This GitHub repo is for issues with the website itself, and not for support on minecraft servers/crashes or client crashes.

Since you got issues with curseforge I suggest you ask the support team from curseforge to help with your problem 

Have a good day!
